package com.example.repogram;

import java.util.ArrayList;

public class DataSource {
    public static ArrayList<Account> accounts = generateDummyAccounts();

    private static ArrayList<Account> generateDummyAccounts() {
        ArrayList<Account> accounts = new ArrayList<>();
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        accounts.add(new Account("medievalhistoryart", "1.465", "228RB", "98", R.drawable.profile_medievalhistoryart_pp, R.drawable.profile_medievalhistoryart_post1, R.drawable.profile_medievalhistoryart_post2, R.drawable.profile_medievalhistoryart_post3, R.drawable.profile_medievalhistoryart_post4, null, null, null, null, null, R.drawable.profile_medievalhistoryart_story));
        return accounts;
    }
}
